name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  check:
    name: Check Changes in Website Files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install -r requirements.txt
      - name: check modified files
        id: check_files
        working-directory: .github/scripts
        run: 
          python check_website.py

