name: Testing Workflow

on:
  push:
    branches:
    - testing

jobs:
  check:
    name: Check Changes in Website Files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
            # Step 4: Checkout
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # Step 1: Setup Pyton
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Step 3: Run python script
      - name: check modified files
        id: check_files
        working-directory: .github/scripts
        run: |
          python check_website.py


  # Job 2: Upload File to S3
  deploy:
    name: Upload File to S3
    needs: check
    if: needs.check.outputs.run_job == 'False'
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code 
    - name: Checkout Code 
      uses: actions/checkout@master
      # Step 2: Upload Files to S3
    - uses: anhlead/s3-sync-action-clone@master
      with:
        args: --acl public-read --follow-symlinks --delete 
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'website'      # optional: defaults to entire repository
