name: Testing Workflow

on:
  push:
    branches:
    - testing

jobs:
  check:
    name: Check Changes in Website Files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
            # Step 4: Checkout
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # Step 1: Setup Pyton
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Step 3: Run python script
      - name: check modified files
        id: check_files
        working-directory: .github/scripts
        run: 
          python check_website.py


