name: "Terraform-Plan-Infra-Plan"


on:
  push:
    branches:
      - mainfeaturebranch
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID}}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_ID}}
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color


